// Everything a guest reads. Every key must exist in both `th` and `en`.

export const STRINGS = {
  th: {
    title: 'ค้นหาบูธ',
    subtitle: 'สัปดาห์หนังสือแห่งชาติ ครั้งที่ 54 · ศูนย์ฯ สิริกิติ์ ฮอลล์ 5–8',
    searchLabel: 'ค้นหาบูธหรือสำนักพิมพ์',
    ph: 'เลขบูธ (เช่น K16) หรือชื่อสำนักพิมพ์',
    quick: 'ไปที่ยอดนิยม',
    legend: 'สีของโซน',
    noRes: (q) => `ไม่พบ “${q}” ลองพิมพ์เลขบูธ เช่น K16 หรือชื่อสำนักพิมพ์`,
    hall: (h) => `ฮอลล์ ${h}`,
    outside: 'หน้าฮอลล์',
    aisle: (l) => `ทางเดิน ${l}`,
    from: 'คุณอยู่ที่ไหนตอนนี้',
    pickFrom: 'เลือกจุดเริ่มต้น',
    pickHint: 'เลือกจุดที่คุณอยู่ แล้วแอปจะวาดเส้นทางเดินให้',
    min: (m) => `ประมาณ ${m} นาที`,
    meters: 'ม.',
    s_start: (n) => `เริ่มที่${n}`,
    s_door: (n) => `เข้างานทาง${n}`,
    s_hall: (h) => `เดินต่อเข้าฮอลล์ ${h}`,
    s_aisle: (l) => `เลี้ยวเข้าทางเดิน ${l} (ตัวอักษรตามแนวผนังด้านใน)`,
    s_pos: {
      back: 'บูธอยู่ช่วงท้ายทางเดิน ใกล้ผนังด้านใน',
      mid: 'บูธอยู่ประมาณกลางทางเดิน',
      front: 'บูธอยู่ช่วงต้นทางเดิน ใกล้ประตูฝั่งทะเลสาบ',
    },
    s_arrive: (c) => `ถึงบูธ ${c} แล้ว ดูจุดที่ไฮไลต์บนแผนที่`,
    s_arrivePlace: (n) => `ถึง${n}แล้ว`,
    same: 'คุณอยู่ที่นี่แล้ว',
    clear: 'ล้างเส้นทาง',
    share: 'คัดลอกลิงก์',
    copied: 'คัดลอกลิงก์แล้ว',
    hide: 'ย่อ',
    show: 'ขยาย',
    zoomIn: 'ซูมเข้า',
    zoomOut: 'ซูมออก',
    fit: 'ดูทั้งผัง',
    clearSearch: 'ล้างคำค้นหา',
    groups: { entry: 'ทางเข้า', wc: 'ห้องน้ำ', info: 'จุดประชาสัมพันธ์', charge: 'จุดชาร์จแบต', stage: 'เวทีและกิจกรรม', other: 'อื่น ๆ' },
    publishers: 'สำนักพิมพ์ในบูธนี้',
    tapHint: 'แตะบูธบนแผนที่ หรือพิมพ์ค้นหาด้านบน',
    noRoute: 'ไม่พบเส้นทาง ลองเลือกจุดเริ่มต้นอื่น',
  },
  en: {
    title: 'Booth Finder',
    subtitle: '54th National Book Fair · QSNCC Halls 5–8',
    searchLabel: 'Search booths or publishers',
    ph: 'Booth code (e.g. K16) or publisher',
    quick: 'Popular places',
    legend: 'Zone colours',
    noRes: (q) => `Nothing matches “${q}”. Try a booth code like K16 or a publisher name.`,
    hall: (h) => `Hall ${h}`,
    outside: 'Outside the halls',
    aisle: (l) => `Aisle ${l}`,
    from: 'Where are you now?',
    pickFrom: 'Choose a starting point',
    pickHint: 'Pick where you are and the map draws your walking route.',
    min: (m) => `about ${m} min`,
    meters: 'm',
    s_start: (n) => `Start at ${n}.`,
    s_door: (n) => `Go in through the ${n}.`,
    s_hall: (h) => `Keep walking into Hall ${h}.`,
    s_aisle: (l) => `Turn into aisle ${l}. Aisle letters run along the back wall.`,
    s_pos: {
      back: 'The booth is near the back-wall end of the aisle.',
      mid: 'The booth is about halfway along the aisle.',
      front: 'The booth is near the lakeside end of the aisle.',
    },
    s_arrive: (c) => `You're at booth ${c}. It's highlighted on the map.`,
    s_arrivePlace: (n) => `You've reached ${n}.`,
    same: "You're already here.",
    clear: 'Clear route',
    share: 'Copy link',
    copied: 'Link copied',
    hide: 'Less',
    show: 'More',
    zoomIn: 'Zoom in',
    zoomOut: 'Zoom out',
    fit: 'Show whole floor',
    clearSearch: 'Clear search',
    groups: { entry: 'Entrances', wc: 'Toilets', info: 'Information', charge: 'Charging spots', stage: 'Stages & activities', other: 'Other' },
    publishers: 'At this booth',
    tapHint: 'Tap a booth on the map, or search above.',
    noRoute: 'No route found. Try a different starting point.',
  },
};

/** Booth categories, colours matched to the printed legend. `cat` values in booths.json. */
export const CATEGORIES = {
  kids: { color: '#F58BB8', th: 'หนังสือเด็กและการศึกษา', en: "Children's & educational" },
  fiction: { color: '#E3452F', th: 'นิยายและวรรณกรรม', en: 'Fiction & literature' },
  bl: { color: '#9C7DBA', th: "หนังสือ Boy's Love / Girl's Love", en: "Boy's Love & Girl's Love" },
  intl: { color: '#FFCB05', th: 'หนังสือต่างประเทศ', en: 'International books', darkText: true },
  rare: { color: '#C4884A', th: 'หนังสือเก่า', en: 'Rare books' },
  general: { color: '#1F84C6', th: 'หนังสือทั่วไป', en: 'General books' },
  comic: { color: '#F68C22', th: 'หนังสือการ์ตูนและวัยรุ่น', en: 'Comics & light novels' },
  nonbook: { color: '#5DBB6D', th: 'Non Books (สื่อการศึกษา/บอร์ดเกม)', en: 'Non-books & board games' },
  special: { color: '#1D2442', th: 'นิทรรศการและเวที', en: 'Exhibitions & stages' },
};

/**
 * Names for exhibition booths and foyer zones, read from the printed plan.
 * `short` is drawn inside large booths on the map.
 * U04, U06 and A10 were hard to read on the source image; confirm with the organiser.
 */
export const ZONES = {
  A02: { th: "เวที Author's Salon", en: "Author's Salon stage", short: "AUTHOR'S SALON" },
  T02: { th: 'เวที Meet the Legends', en: 'Meet the Legends stage', short: 'MEET THE LEGENDS' },
  A26: { th: 'PUBAT Shop', en: 'PUBAT Shop' },
  A31: { th: 'นิทรรศการ Y Book Journey ย้อนรอยตำนานวายจากไทยสู่โลก', en: 'Y Book Journey exhibition' },
  A15: { th: 'โครงการประกวดหนังสือระดับชาติ', en: 'National book award exhibition' },
  A16: { th: 'นิทรรศการอ่านพุทธ ตำนานผ่านบรรณพิภพ', en: 'Buddhist literature exhibition' },
  B15: { th: 'นิทรรศการวรรณกรรมแห่งชาติ', en: 'National literature exhibition' },
  A10: { th: 'นิทรรศการจากวิถีแห่งศรัทธา สู่ภูมิปัญญาของยุคสมัย', en: 'Faith and wisdom exhibition' },
  U01: { th: 'มูลนิธิหนึ่งอ่านล้านตื่น × เจ้าขุนทองและผองเพื่อน', en: 'One Read Million Wake Foundation × Khun Thong & friends' },
  U02: { th: 'Little Read Universe: Legend Alive จักรวาลตำนานมีชีวิต', en: 'Little Read Universe: Legend Alive' },
  U03: { th: 'จุดประชาสัมพันธ์ / จุดฝากของ (ฝั่ง MRT)', en: 'Information & bag drop (MRT side)' },
  U04: { th: 'นิทรรศการ U04', en: 'Exhibition U04' },
  U05: { th: 'นิทรรศการ Read the Legend: หนังสือต้องห้าม (ลืม)', en: 'Read the Legend: the forbidden (forgotten) books' },
  U06: { th: 'นิทรรศการ U06', en: 'Exhibition U06' },
  U07: { th: 'นิทรรศการ Read the Legend: หนังสือต้องห้าม (ลืม)', en: 'Read the Legend: the forbidden (forgotten) books' },
  U08: { th: 'นิทรรศการเส้นทางวรรณกรรม รางวัลพานแว่นฟ้า 25 ปี', en: '25 years of the Phan Waen Fa literary award' },
  U09: { th: 'Press / Information · กิจกรรม Legend Trail Bingo', en: 'Press & information · Legend Trail Bingo' },
  U10: { th: 'นิทรรศการแสงแห่งปัญญาในสมเด็จพระพันปีหลวง', en: 'Royal exhibition: Light of Wisdom' },
  U11: { th: 'นิทรรศการหนังสือดีเด่น ประจำปี 2569', en: 'Outstanding Books of 2026' },
};

const L = (id, group, x, y, th, en, icon) => ({ id, group, x, y, th, en, icon });

/** Starting points and non-booth destinations. `id` appears in share links (#from=…), so keep ids stable. */
export const LANDMARKS = [
  L('mrt', 'entry', 252, 560, 'สถานี MRT ศูนย์ฯ สิริกิติ์ (ทางออก 3)', 'MRT QSNCC station (exit 3)', 'mrt'),
  L('west', 'entry', 418, 880, 'ประตูฮอลล์ 5 ฝั่ง MRT', 'Hall 5 door, MRT side', 'door'),
  L('door5', 'entry', 687, 1500, 'ประตูฮอลล์ 5 ฝั่งทะเลสาบ', 'Hall 5 lakeside door', 'door'),
  L('door6', 'entry', 1247, 1500, 'ประตูฮอลล์ 6 ฝั่งทะเลสาบ', 'Hall 6 lakeside door', 'door'),
  L('door7', 'entry', 1799, 1500, 'ประตูฮอลล์ 7 ฝั่งทะเลสาบ', 'Hall 7 lakeside door', 'door'),
  L('door8', 'entry', 2333, 1500, 'ประตูฮอลล์ 8 ฝั่งทะเลสาบ', 'Hall 8 lakeside door', 'door'),
  L('wc1', 'wc', 874, 280, 'ห้องน้ำ ฮอลล์ 6 (ผนังด้านใน)', 'Toilets, Hall 6 back wall', 'wc'),
  L('wc2', 'wc', 1428, 280, 'ห้องน้ำ ฮอลล์ 7 (ผนังด้านใน)', 'Toilets, Hall 7 back wall', 'wc'),
  L('wc3', 'wc', 1973, 280, 'ห้องน้ำ ฮอลล์ 8 (ผนังด้านใน)', 'Toilets, Hall 8 back wall', 'wc'),
  L('wc4', 'wc', 874, 1462, 'ห้องน้ำ ฮอลล์ 6 (ฝั่งทะเลสาบ)', 'Toilets, Hall 6 lakeside', 'wc'),
  L('wc5', 'wc', 1428, 1462, 'ห้องน้ำ ฮอลล์ 7 (ฝั่งทะเลสาบ)', 'Toilets, Hall 7 lakeside', 'wc'),
  L('wc6', 'wc', 1974, 1462, 'ห้องน้ำ ฮอลล์ 8 (ฝั่งทะเลสาบ)', 'Toilets, Hall 8 lakeside', 'wc'),
  L('info1', 'info', 571, 1532, 'จุดประชาสัมพันธ์/ฝากของ หน้าฮอลล์ 5', 'Information & bag drop, Hall 5', 'info'),
  L('info2', 'info', 1119, 1530, 'จุดประชาสัมพันธ์/ฝากของ หน้าฮอลล์ 6', 'Information & bag drop, Hall 6', 'info'),
  L('info3', 'info', 1664, 1531, 'Press / Information (U09)', 'Press & information (U09)', 'info'),
  L('info4', 'info', 2211, 1530, 'จุดประชาสัมพันธ์/ฝากของ หน้าฮอลล์ 8', 'Information & bag drop, Hall 8', 'info'),
  L('info5', 'info', 343, 1116, 'จุดประชาสัมพันธ์/ฝากของ ฝั่ง MRT (U03)', 'Information & bag drop, MRT side (U03)', 'info'),
  L('ch1', 'charge', 663, 1136, 'Charge Spot ฮอลล์ 5 (กลางฮอลล์)', 'Charge spot, middle of Hall 5', 'charge'),
  L('ch2', 'charge', 618, 1446, 'Charge Spot ฮอลล์ 5', 'Charge spot, Hall 5 lakeside', 'charge'),
  L('ch3', 'charge', 1163, 1450, 'Charge Spot ฮอลล์ 6', 'Charge spot, Hall 6 lakeside', 'charge'),
  L('ch4', 'charge', 1714, 1450, 'Charge Spot ฮอลล์ 7', 'Charge spot, Hall 7 lakeside', 'charge'),
  L('stage', 'stage', 2219, 822, 'เวทีกลาง (ฮอลล์ 8)', 'Main stage (Hall 8)', 'stage'),
  L('lift', 'other', 384, 1530, 'ลิฟต์ไปห้องสัมมนา ชั้น 2', 'Lift to seminar rooms, level 2', 'lift'),
];

export const GROUP_ORDER = ['entry', 'wc', 'info', 'charge', 'stage', 'other'];

/** Chips on the idle screen: ['booth', code] or ['place', landmarkId]. */
export const QUICK_PICKS = [['booth', 'A02'], ['booth', 'T02'], ['place', 'stage'], ['booth', 'A26'], ['place', 'wc2'], ['place', 'info2']];
